
###### INSTALL PACKAGES #####
install.packages("rgbif")
install.packages("rnaturalearth")
install.packages("raster")
install.packages("ggplot2")
install.packages("sf")
install.packages("sp")
install.packages("geodata")
install_github("ropensci/MODIStsp")
remotes::install_github("wmgeolab/rgeoboundaries")
install.packages("ggfortify")
install.packages("elevatr")
install.packages("rnaturalearthdata")
install.packages("rayshader")
install.packages("vegan")
install.packages("eks")
install.packages("devtools")
library(devtools)
devtools::install_github("ropensci/rnaturalearthhires")
install.packages("stats")
install.packages("plotly")
install.packages("imagefx")
install.packages("corrplot")
